In [1]:
import snscrape.modules.twitter as sntwitter
import itertools
import re
import numpy as np
import pandas as pd
from textblob import TextBlob
import nltk
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = '"#IPL2019 near:India" since:2019-01-01 until:2021-01-01 lang:en'
maxTweets = 3000
tweetList = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(data).get_items()):
    if i > maxTweets:
         break 
    tweetList.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.likeCount, tweet.retweetCount, tweet.user.followersCount])

In [3]:
India = pd.DataFrame(tweetList, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'LikeCount', 'Retweet', 'Followers'])
India['location'] = 'India'                                         
India

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location
0,2020-11-10 22:41:10+00:00,1326293851645112325,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,4,0,2003,India
1,2020-11-02 11:55:10+00:00,1323232176855416832,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,0,0,171,India
2,2020-10-26 20:28:20+00:00,1320824604752052228,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,0,0,1055,India
3,2020-10-26 18:04:24+00:00,1320788385405915136,Why did not select #SuryakumarYadav he is a pe...,thirupgp,0,0,434,India
4,2020-10-25 13:29:47+00:00,1320356885640347648,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,0,0,1055,India
...,...,...,...,...,...,...,...,...
2996,2019-04-21 16:33:27+00:00,1120002617856315392,Where were you @DaleSteyn62 !! Absolute class....,Mihir_Kaslikar,0,0,146,India
2997,2019-04-21 16:33:17+00:00,1120002574705250309,Styen is on fire. Even though i am a csk suppo...,rush13x,1,0,142,India
2998,2019-04-21 16:33:02+00:00,1120002512306806784,the styen gun.....\n\n#IPL2019 #RCBvCSK,mgmohitgrover,0,0,892,India
2999,2019-04-21 16:30:56+00:00,1120001985539739648,A classic Dale Steyn wicket. Pure joy !!\n#IPL...,monutweetstasty,1,0,154,India
3000,2019-04-21 16:28:25+00:00,1120001352103538693,Whom rooting for tonight #RCBvCSK #IPL2019 #IP...,coolshalabh2010,0,0,971,India

In [4]:
data = '"#IPL2019 near:UK" since:2019-01-01 until:2021-01-01 lang:en'
maxTweets = 3000
tweetList = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(data).get_items()):
    if i > maxTweets:
         break 
    tweetList.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.likeCount, tweet.retweetCount, tweet.user.followersCount])

In [5]:
uk = pd.DataFrame(tweetList, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'LikeCount', 'Retweet', 'Followers'])
uk['location'] = 'UK'
uk

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location
0,2019-06-22 17:52:42+00:00,1142490610642931713,Very good cricket match today.. Good to see Af...,desairahul,0,0,1725,UK
1,2019-06-15 17:33:25+00:00,1139949043923247105,Back in the days there were exciting cheers in...,taurusv29,0,0,56,UK
2,2019-05-28 14:07:44+00:00,1133374297714700288,#IPL2019 has not gone much in favour of our pl...,Ankit77Thakur,1,0,764,UK
3,2019-05-16 13:44:52+00:00,1129019888067129344,@BCCI No more #axarpatel or #ambatirayudu for ...,vivek__malhotra,1,0,158,UK
4,2019-05-15 06:17:18+00:00,1128544866789675008,#IPL2019 might be over - congrats @mipaltan 😀 ...,natalietoms,2,0,858,UK
...,...,...,...,...,...,...,...,...
533,2019-02-20 08:22:06+00:00,1098135695762296832,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,0,0,181,UK
534,2019-02-03 12:58:53+00:00,1092044754852945921,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,5,2,4043,UK
535,2019-02-03 12:18:30+00:00,1092034591035215872,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,0,0,28,UK
536,2019-01-16 19:53:45+00:00,1085626176377376769,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,0,0,1765,UK
537,2019-01-08 11:29:46+00:00,1082600244091719681,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,0,0,1498,UK

In [6]:
#concatinate both dataframes
df = pd.concat([India, uk], axis=0)
df.reset_index(drop=True, inplace=True)
df

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location
0,2020-11-10 22:41:10+00:00,1326293851645112325,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,4,0,2003,India
1,2020-11-02 11:55:10+00:00,1323232176855416832,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,0,0,171,India
2,2020-10-26 20:28:20+00:00,1320824604752052228,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,0,0,1055,India
3,2020-10-26 18:04:24+00:00,1320788385405915136,Why did not select #SuryakumarYadav he is a pe...,thirupgp,0,0,434,India
4,2020-10-25 13:29:47+00:00,1320356885640347648,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,0,0,1055,India
...,...,...,...,...,...,...,...,...
3534,2019-02-20 08:22:06+00:00,1098135695762296832,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,0,0,181,UK
3535,2019-02-03 12:58:53+00:00,1092044754852945921,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,5,2,4043,UK
3536,2019-02-03 12:18:30+00:00,1092034591035215872,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,0,0,28,UK
3537,2019-01-16 19:53:45+00:00,1085626176377376769,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,0,0,1765,UK
3538,2019-01-08 11:29:46+00:00,1082600244091719681,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,0,0,1498,UK

## Data Preprocessing

In [7]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub("@[\w]*", "", text)
    text = re.sub("http\S+", "", text)
    text = re.sub("[^a-zA-Z#]", " ", text)
    text = re.sub("rt", "", text)
    text = re.sub("\s+", " ", text)

    return text

In [8]:
df['Clean_Text'] = df['Text'].apply(preprocess_text)
df

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location,Clean_Text
0,2020-11-10 22:41:10+00:00,1326293851645112325,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,4,0,2003,India,i remember mahela jayawardena victory speech i...
1,2020-11-02 11:55:10+00:00,1323232176855416832,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,0,0,171,India,you will be remembered sir but i can t control...
2,2020-10-26 20:28:20+00:00,1320824604752052228,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,0,0,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...
3,2020-10-26 18:04:24+00:00,1320788385405915136,Why did not select #SuryakumarYadav he is a pe...,thirupgp,0,0,434,India,why did not select #suryakumaryadav he is a pe...
4,2020-10-25 13:29:47+00:00,1320356885640347648,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,0,0,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...
...,...,...,...,...,...,...,...,...,...
3534,2019-02-20 08:22:06+00:00,1098135695762296832,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,0,0,181,UK,oooh yes #ipl let the games begin #excited
3535,2019-02-03 12:58:53+00:00,1092044754852945921,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,5,2,4043,UK,thank you #kkracademy for turning great playe...
3536,2019-02-03 12:18:30+00:00,1092034591035215872,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,0,0,28,UK,#ipl i ve been told you won t be broadcasting...
3537,2019-01-16 19:53:45+00:00,1085626176377376769,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,0,0,1765,UK,also need a tv by april #ipl and then #iccworl...
3538,2019-01-08 11:29:46+00:00,1082600244091719681,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,0,0,1498,UK,fir ordered against #anupamkher others for #ac...

In [9]:
def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

def getPolarity(text):
    return TextBlob(text).sentiment.polarity


df['Subjectivity'] = df['Clean_Text'].apply(getSubjectivity)
df['Polarity'] = df['Clean_Text'].apply(getPolarity)
df

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location,Clean_Text,Subjectivity,Polarity
0,2020-11-10 22:41:10+00:00,1326293851645112325,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,4,0,2003,India,i remember mahela jayawardena victory speech i...,0.233333,0.400000
1,2020-11-02 11:55:10+00:00,1323232176855416832,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,0,0,171,India,you will be remembered sir but i can t control...,0.860000,0.300000
2,2020-10-26 20:28:20+00:00,1320824604752052228,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,0,0,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,0.133333,0.266667
3,2020-10-26 18:04:24+00:00,1320788385405915136,Why did not select #SuryakumarYadav he is a pe...,thirupgp,0,0,434,India,why did not select #suryakumaryadav he is a pe...,0.625000,0.625000
4,2020-10-25 13:29:47+00:00,1320356885640347648,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,0,0,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
3534,2019-02-20 08:22:06+00:00,1098135695762296832,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,0,0,181,UK,oooh yes #ipl let the games begin #excited,0.750000,0.375000
3535,2019-02-03 12:58:53+00:00,1092044754852945921,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,5,2,4043,UK,thank you #kkracademy for turning great playe...,0.875000,0.733333
3536,2019-02-03 12:18:30+00:00,1092034591035215872,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,0,0,28,UK,#ipl i ve been told you won t be broadcasting...,0.325000,0.175000
3537,2019-01-16 19:53:45+00:00,1085626176377376769,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,0,0,1765,UK,also need a tv by april #ipl and then #iccworl...,0.000000,0.000000
3538,2019-01-08 11:29:46+00:00,1082600244091719681,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,0,0,1498,UK,fir ordered against #anupamkher others for #ac...,0.000000,0.000000

In [10]:
def getAnalysis(score):
    if score<0:
        return 'Negative'
    elif score == 0:
        return 'Nuetral'
    else:
        return 'Positive'
    
df['Analysis'] = df['Polarity'].apply(getAnalysis)
df

,Datetime,Tweet Id,Text,Username,LikeCount,Retweet,Followers,location,Clean_Text,Subjectivity,Polarity,Analysis
0,2020-11-10 22:41:10+00:00,1326293851645112325,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,4,0,2003,India,i remember mahela jayawardena victory speech i...,0.233333,0.400000,Positive
1,2020-11-02 11:55:10+00:00,1323232176855416832,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,0,0,171,India,you will be remembered sir but i can t control...,0.860000,0.300000,Positive
2,2020-10-26 20:28:20+00:00,1320824604752052228,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,0,0,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,0.133333,0.266667,Positive
3,2020-10-26 18:04:24+00:00,1320788385405915136,Why did not select #SuryakumarYadav he is a pe...,thirupgp,0,0,434,India,why did not select #suryakumaryadav he is a pe...,0.625000,0.625000,Positive
4,2020-10-25 13:29:47+00:00,1320356885640347648,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,0,0,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,0.000000,0.000000,Nuetral
...,...,...,...,...,...,...,...,...,...,...,...,...
3534,2019-02-20 08:22:06+00:00,1098135695762296832,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,0,0,181,UK,oooh yes #ipl let the games begin #excited,0.750000,0.375000,Positive
3535,2019-02-03 12:58:53+00:00,1092044754852945921,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,5,2,4043,UK,thank you #kkracademy for turning great playe...,0.875000,0.733333,Positive
3536,2019-02-03 12:18:30+00:00,1092034591035215872,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,0,0,28,UK,#ipl i ve been told you won t be broadcasting...,0.325000,0.175000,Positive
3537,2019-01-16 19:53:45+00:00,1085626176377376769,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,0,0,1765,UK,also need a tv by april #ipl and then #iccworl...,0.000000,0.000000,Nuetral
3538,2019-01-08 11:29:46+00:00,1082600244091719681,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,0,0,1498,UK,fir ordered against #anupamkher others for #ac...,0.000000,0.000000,Nuetral

In [11]:
df['Analysis'].value_counts()

Positive    1765
Nuetral     1271
Negative     503
Name: Analysis, dtype: int64

In [12]:
df['User_engagement'] = df['LikeCount'] + df['Retweet']

In [13]:
df = df.drop(columns=[ 'Datetime', 'Tweet Id', 'Subjectivity', 'Polarity', 'LikeCount', 'Retweet'])
df

,Text,Username,Followers,location,Clean_Text,Analysis,User_engagement
0,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,2003,India,i remember mahela jayawardena victory speech i...,Positive,4
1,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,171,India,you will be remembered sir but i can t control...,Positive,0
2,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,Positive,0
3,Why did not select #SuryakumarYadav he is a pe...,thirupgp,434,India,why did not select #suryakumaryadav he is a pe...,Positive,0
4,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,Nuetral,0
...,...,...,...,...,...,...,...
3534,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,181,UK,oooh yes #ipl let the games begin #excited,Positive,0
3535,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,4043,UK,thank you #kkracademy for turning great playe...,Positive,7
3536,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,28,UK,#ipl i ve been told you won t be broadcasting...,Positive,0
3537,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,1765,UK,also need a tv by april #ipl and then #iccworl...,Nuetral,0
3538,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,1498,UK,fir ordered against #anupamkher others for #ac...,Nuetral,0

In [14]:
#df.to_csv("twiteer_scraping")

In [15]:
# Individualism
def Individualness(tweets):
#     mt=0
    mentions = []
    for tweet in tweets:
        it=tweet.split()
        mt=it.count("i")+it.count("me")+it.count("my")+it.count("own")+it.count("able")
        mentions.append(mt)
    #print(mentions)
    return mentions

In [16]:
# score = collectiveness(df['Text'])
# print(score)

In [17]:
df['individualism'] = Individualness(df['Clean_Text'])

In [18]:
df

,Text,Username,Followers,location,Clean_Text,Analysis,User_engagement,individualism
0,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,2003,India,i remember mahela jayawardena victory speech i...,Positive,4,1
1,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,171,India,you will be remembered sir but i can t control...,Positive,0,2
2,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,Positive,0,0
3,Why did not select #SuryakumarYadav he is a pe...,thirupgp,434,India,why did not select #suryakumaryadav he is a pe...,Positive,0,0
4,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,Nuetral,0,0
...,...,...,...,...,...,...,...,...
3534,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,181,UK,oooh yes #ipl let the games begin #excited,Positive,0,0
3535,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,4043,UK,thank you #kkracademy for turning great playe...,Positive,7,0
3536,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,28,UK,#ipl i ve been told you won t be broadcasting...,Positive,0,1
3537,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,1765,UK,also need a tv by april #ipl and then #iccworl...,Nuetral,0,0
3538,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,1498,UK,fir ordered against #anupamkher others for #ac...,Nuetral,0,0

In [19]:
#collectivism
def collectiveness(tweets):
#     mt=0
    mentions = []
    for tweet in tweets:
        it=tweet.split()
        mt=it.count("we")+it.count("us")+it.count("our")+it.count("ourselves")+it.count("lets")
        mentions.append(mt)
    #print(mentions)
    return mentions

In [20]:
df['collectivism'] = collectiveness(df['Clean_Text'])
df

,Text,Username,Followers,location,Clean_Text,Analysis,User_engagement,individualism,collectivism
0,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,2003,India,i remember mahela jayawardena victory speech i...,Positive,4,1,3
1,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,171,India,you will be remembered sir but i can t control...,Positive,0,2,1
2,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,Positive,0,0,0
3,Why did not select #SuryakumarYadav he is a pe...,thirupgp,434,India,why did not select #suryakumaryadav he is a pe...,Positive,0,0,0
4,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,Nuetral,0,0,0
...,...,...,...,...,...,...,...,...,...
3534,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,181,UK,oooh yes #ipl let the games begin #excited,Positive,0,0,0
3535,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,4043,UK,thank you #kkracademy for turning great playe...,Positive,7,0,0
3536,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,28,UK,#ipl i ve been told you won t be broadcasting...,Positive,0,1,0
3537,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,1765,UK,also need a tv by april #ipl and then #iccworl...,Nuetral,0,0,0
3538,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,1498,UK,fir ordered against #anupamkher others for #ac...,Nuetral,0,0,0

In [21]:
#powerdistance
def tags(tweets):
#     mt=0
    mentions = []
    for tweet in tweets:
        it=tweet.split()
        mt=it.count("@")
        mentions.append(mt)
    #print(mentions)
    return mentions

In [22]:
df['Power_distance'] = tags(df['Text'])
df

,Text,Username,Followers,location,Clean_Text,Analysis,User_engagement,individualism,collectivism,Power_distance
0,I remember Mahela Jayawardena Victory speech i...,JameelHassan32,2003,India,i remember mahela jayawardena victory speech i...,Positive,4,1,3,0
1,You will be remembered sir @ShaneRWatson33 \nB...,Shanak_Msd,171,India,you will be remembered sir but i can t control...,Positive,0,2,1,0
2,Back to back win | #punjab #kxip #kxipvkkr #kk...,smasdaque,1055,India,back to back win #punjab #kxip #kxipvkkr #kkr ...,Positive,0,0,0,1
3,Why did not select #SuryakumarYadav he is a pe...,thirupgp,434,India,why did not select #suryakumaryadav he is a pe...,Positive,0,0,0,0
4,CSK won | #csk #cskfans #csktrolls #cşk #cskre...,smasdaque,1055,India,csk won #csk #cskfans #csktrolls #c k #cskretu...,Nuetral,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
3534,oooh yes..#IPL2019 let the games begin #excite...,KhotSharmila,181,UK,oooh yes #ipl let the games begin #excited,Positive,0,0,0,0
3535,@KKRiders @rinkusingh235 @abhisheknayar1 Thank...,Misty4SRK,4043,UK,thank you #kkracademy for turning great playe...,Positive,7,0,0,0
3536,@SkySports @SkyCricket #IPL2019 I’ve been told...,alisonbarnesey,28,UK,#ipl i ve been told you won t be broadcasting...,Positive,0,1,0,0
3537,Also... need a TV by April. #IPL2019 and then ...,MissAmilahS,1765,UK,also need a tv by april #ipl and then #iccworl...,Nuetral,0,0,0,0
3538,"FIR ordered against #AnupamKher, 16 others for...",aaliyagoyel1,1498,UK,fir ordered against #anupamkher others for #ac...,Nuetral,0,0,0,0

In [23]:
df['Text'][0]

'I remember Mahela Jayawardena Victory speech in Last Year IPL2019 \n\n‘’Yes We Don’t Have Purple Cap, We Don’t Have Orange Cap But who cares ? \nWe have that Trophy ‘’ 🤩👏🏻\n\nAnd today they win the trophy without Orange and purple caps 😉 @MahelaJay @mipaltan'

In [24]:
df['Text'][1]

"You will be remembered sir @ShaneRWatson33 \nBut I can't control my tears \nYour innings against MI in #IPL2019 final and your innings in #Ipl2018 final against @SunRisers is unforgettable \nThank you sir for your Sweet sweet Memories for our @ChennaiIPL \n\nAlways a champ https://t.co/q1q9fPyuBW"

In [25]:
df['Text'][3532]

"Who's going to win the IPL this year then? #IPL2019"

In [26]:
# extract @mentions
def mentions_extract(tweets):
    mentions = []
    for tweet in tweets:
        mt = re.findall(r"@(\w+)", tweet)
        mentions.append(mt)
    return mentions

In [27]:
mt = mentions_extract(df['Clean_Text'])

In [28]:
mt = sum(mt, [])

In [30]:
mt

[]

In [ ]:
freq = nltk.FreqDist(ht)
d = pd.DataFrame({'Hashtag': list(freq.keys()),
                 'Count': list(freq.values())})
d.head()

In [31]:
# extract the hashtag
def hashtag_extract(tweets):
    hashtags = []
    # loop words in the tweet
    for tweet in tweets:
        ht = re.findall(r"#(\w+)", tweet)
        hashtags.append(ht)
    return hashtags

In [32]:
ht = hashtag_extract(df['Clean_Text'])

In [33]:
ht = sum(ht, [])

In [34]:
freq = nltk.FreqDist(ht)
d = pd.DataFrame({'Hashtag': list(freq.keys()),
                 'Count': list(freq.values())})
d.head()

    Hashtag  Count
0       ipl   4377
1    punjab      4
2      kxip     56
3  kxipvkkr     37
4       kkr    129

In [ ]:
# select top 10 hashtags
d = d.nlargest(columns='Count', n=10)
plt.figure(figsize=(15,9))
sns.barplot(data=d, x='Hashtag', y='Count')
plt.show()

In [ ]:
# individual words considered as tokens
tokenized_tweet = df['Clean_Text'].apply(lambda x: x.split())
tokenized_tweet.head()

In [ ]:
# stem the words
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

tokenized_tweet = tokenized_tweet.apply(lambda sentence: [stemmer.stem(word) for word in sentence])
tokenized_tweet.head()

In [ ]:
# combine words into single sentence
for i in range(len(tokenized_tweet)):
    tokenized_tweet[i] = " ".join(tokenized_tweet[i])
    
df['Clean_Texts'] = tokenized_tweet
df.head()